pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                GOCACHE      = "${WORKSPACE}/.cache/go-build"
                GOPATH       = "${WORKSPACE}/.go"
                GOMODCACHE   = "${WORKSPACE}/.go/pkg/mod"
                HOME         = "${WORKSPACE}"
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
